### PR TITLE
hotfix: psalm regression after updating to 1.2.0

### LINKED ISSUE #10: Assert::isMap in HtpasswdFactory leads to Exception: 'Expected map - associative array with string keys.'
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.2.0

#### Summary

After running `composer update` HtpasswdFactory does not work anymore. While debugging I could figure out that `Assert::isMap($config)` leads to a `InvalidArgumentException` with message 'Expected map - associative array with string keys.'
When I comment this line everything works as excepted.

#### Current behavior

Application terminates with Error 500 caused by InvalidArgumentException

#### How to reproduce

I don't know...

my config looks like this:

```
[
    'authentication' => [
        'realm' => 'doc',
        'htpasswd' => __DIR__ . "/../config/htpasswd",
    ]
]
```

#### Expected behavior

Htpasswd object will be returned.

### PR DESCRIPTION
**Pull request by boesing**
|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### Description

As mezzio supports multiple containers (which may only return objects), we have to cast the `ArrayObject` to an array to make a proper assertion.

Related container configurations:

https://github.com/jsoumelidis/zend-sf-di-config/blob/master/src/Config.php#L88
https://github.com/laminas/laminas-auradi-config/blob/2.1.x/src/Config.php#L66

Fixes #10 
Closes #10

### CODE REVIEW

File: src/UserRepository/HtpasswdFactory.php [hunk 1]
```diff
@@ -24,9 +24,10 @@ class HtpasswdFactory
      */
     public function __invoke(ContainerInterface $container): Htpasswd
     {
-        $config = $container->get('config');
+        $config = (array) $container->get('config');
```
Comment (Xerkus) [inline src/UserRepository/HtpasswdFactory.php]: This might not do what is expected unless it is ArrayObject or `stdObject`.
For stdlib config object we would want to call `toArray();` and for iterable we should probably do `iterator_to_array()`, otherwise reject altogether

Comment (boesing) [reply src/UserRepository/HtpasswdFactory.php]: `stdClass` or `object` won't allow array access and thus would've triggered massive notices in the past, thus I dont really care about that.

With `stdlib config object` you mean `laminas-config`? As this has nothing todo with `laminas-stdlib`, I am a bit confused.

Comment (boesing) [reply src/UserRepository/HtpasswdFactory.php]: `iterator_to_array` would only work if the `$config` is an instance of `IteratorAggregate` but thats not the case if the provided object only provides `ArrayAccess`...

Comment (Xerkus) [reply src/UserRepository/HtpasswdFactory.php]: Yes, i meant laminas-config.
We actually require 'config' to be an array, which poses an issue. It is far reaching issue that I will bring to contributors channel.

File: test/UserRepository/HtpasswdFactoryTest.php [hunk 2]
```diff
@@ -32,6 +34,29 @@ class HtpasswdFactoryTest extends TestCase
...
+                'htpasswd' => $filename,
+            ],
+        ];
+
+        yield 'array' => [
+            $config,
+            $filename,
+        ];
+
+        yield ArrayObject::class => [
```
Comment (Xerkus) [inline test/UserRepository/HtpasswdFactoryTest.php:56]: No point using yield, since it will be converted to array before tests are run

Comment (boesing) [reply test/UserRepository/HtpasswdFactoryTest.php:56]: I prefer yield and tests are green so actually no need to change this as we are using yield in many other packages aswell.

**Review by weierophinney — APPROVED** [review]
:+1: Looks good - minimal code change, but ample tests to validate the approach.

File: src/UserRepository/HtpasswdFactory.php [hunk 3]
```diff
@@ -24,9 +25,10 @@ class HtpasswdFactory
...
     {
-        $config = $container->get('config');
-        Assert::isMap($config);
+        /** @var ArrayAccess<array-key,mixed> $config */
+        $config     = $container->get('config');
         $authConfig = $config['authentication'] ?? [];
+        Assert::isMap($authConfig);
 
         $htpasswd = $authConfig['htpasswd'] ?? null;
         Assert::nullOrString($htpasswd);
```
Comment (Xerkus) [inline src/UserRepository/HtpasswdFactory.php:34]:
```suggestion
        $config   = $container->get('config');
        Assert::isArrayAccessible($config);
        $htpasswd = $config['authentication']['htpasswd'] ?? null;
        Assert::nullOrString($htpasswd);
```
Will this work?

Comment (boesing) [reply src/UserRepository/HtpasswdFactory.php:34]: If `config` may be set as `null` it would crash.
We can keep this in mind for the next major of this and probably want to add some kind of compatibility-layer in `mezzio` itself to wrap any container within a container delegator to ensure that `config` is always an array.

Gonna add this as an RFC in the mezzio project after @weierophinney merged the issue template for RFCs.
